const ADMIN_PIN = '2026';
const STORAGE_KEY = 'imon.clean.release.20260604';
const FRAMES = [
  {angle:0,label:'Front View',src:'assets/model/frame-01.png'},
  {angle:60,label:'Front-Right View',src:'assets/model/frame-02.png'},
  {angle:120,label:'Side-Right View',src:'assets/model/frame-03.png'},
  {angle:180,label:'Rear View',src:'assets/model/frame-04.png'},
  {angle:240,label:'Side-Left View',src:'assets/model/frame-05.png'},
  {angle:300,label:'Front-Left View',src:'assets/model/frame-06.png'}
];
const PROVINCES = [
 ['aceh','Aceh','Sumatra',12,25],['north-sumatra','North Sumatra','Sumatra',17,34],['west-sumatra','West Sumatra','Sumatra',20,44],['riau','Riau','Sumatra',25,42],['riau-islands','Riau Islands','Sumatra',30,38],['jambi','Jambi','Sumatra',27,51],['bengkulu','Bengkulu','Sumatra',25,59],['south-sumatra','South Sumatra','Sumatra',31,59],['bangka-belitung','Bangka Belitung Islands','Sumatra',35,55],['lampung','Lampung','Sumatra',33,69],['jakarta','Jakarta','Java',39,72],['banten','Banten','Java',37,74],['west-java','West Java','Java',43,75],['central-java','Central Java','Java',48,77],['yogyakarta','Yogyakarta','Java',50,80],['east-java','East Java','Java',55,78],['bali','Bali','Bali & Nusa Tenggara',60,82],['west-nusa-tenggara','West Nusa Tenggara','Bali & Nusa Tenggara',64,83],['east-nusa-tenggara','East Nusa Tenggara','Bali & Nusa Tenggara',70,84],['west-kalimantan','West Kalimantan','Kalimantan',47,45],['central-kalimantan','Central Kalimantan','Kalimantan',53,52],['south-kalimantan','South Kalimantan','Kalimantan',56,63],['east-kalimantan','East Kalimantan','Kalimantan',61,50],['north-kalimantan','North Kalimantan','Kalimantan',61,38],['north-sulawesi','North Sulawesi','Sulawesi',72,39],['gorontalo','Gorontalo','Sulawesi',69,45],['central-sulawesi','Central Sulawesi','Sulawesi',67,53],['west-sulawesi','West Sulawesi','Sulawesi',64,62],['south-sulawesi','South Sulawesi','Sulawesi',68,67],['southeast-sulawesi','Southeast Sulawesi','Sulawesi',73,66],['maluku','Maluku','Maluku',80,64],['north-maluku','North Maluku','Maluku',79,51],['southwest-papua','Southwest Papua','Papua',86,58],['west-papua','West Papua','Papua',88,62],['central-papua','Central Papua','Papua',92,62],['papua','Papua','Papua',96,60],['highland-papua','Highland Papua','Papua',93,54],['south-papua','South Papua','Papua',94,72]
].map(([id,name,region,x,y])=>({id,name,region,x,y}));
const SPEAKERS = ['Student Voice','Academic Voice','Community Voice'];
const COMPONENTS = [
 {id:'garuda-wings',name:'Garuda-Inspired Wings',material:'Brushed bronze or bronze-finished stainless steel',meaning:'Dignity, scholarly ascent, Indonesian cultural presence, and the courage to speak globally without erasing local voice.'},
 {id:'sound-spine',name:'Luminous Sound-Wave Spine',material:'Translucent glass or acrylic with internal LED illumination',meaning:'Intelligibility, resonance, rhythm, and the movement of Indonesian English into international academic dialogue.'},
 {id:'book-base',name:'Open-Book Scholarly Base',material:'Bronze relief over a reinforced plinth',meaning:'Teaching, research, publication, and the lecturer’s role in producing knowledge for society.'},
 {id:'archipelago-platform',name:'Archipelago Platform',material:'Dark granite or engineered stone with bronze island inlays',meaning:'Indonesia as a multilingual, multicultural source of global voices.'},
 {id:'qr-station',name:'Interactive QR Audio Stations',material:'Weather-resistant metal, acrylic interface, QR plaque, and optional NFC tag',meaning:'Public access, open education, visitor participation, and living archive interaction.'},
 {id:'paving',name:'Intelligibility Pattern Paving',material:'Engraved stone with waveform and phonetic motifs',meaning:'Speech patterns, intelligibility, rhythm, accent diversity, and ethical listening.'}
];
const HOTSPOTS = [
 {id:'wings',title:'Garuda-Inspired Wings',componentId:'garuda-wings',tags:['Bronze','Heritage','Identity'],desc:'The wings symbolize dignity, ascent, and Indonesian cultural presence in global academic communication. They frame the monument as a public declaration that local accents can carry international meaning.',board:{x:60,y:23,a:'alt'},pos:[{x:54,y:34,a:'right'},{x:55,y:35,a:'right'},{x:57,y:36,a:'right'},{x:49,y:34,a:'left'},{x:43,y:35,a:'left'},{x:43,y:35,a:'left'}]},
 {id:'spine',title:'Luminous Sound-Wave Spine',componentId:'sound-spine',tags:['Glass','LED','Sound'],desc:'The glowing spine visualizes intelligibility, resonance, and the movement of Indonesian voices across borders. It turns speech into light.',board:{x:64,y:31,a:'alt'},pos:[{x:53,y:24,a:'right'},{x:53,y:24,a:'right'},{x:52,y:24,a:'right'},{x:52,y:23,a:'right'},{x:52,y:24,a:'right'},{x:52,y:23,a:'right'}]},
 {id:'book',title:'Open-Book Scholarly Base',componentId:'book-base',tags:['Research','Education','Publication'],desc:'The open book represents teaching, publication, and the lecturer’s contribution to knowledge. It gives the monument an academic foundation.',board:{x:60,y:52,a:'alt'},pos:[{x:52,y:67,a:'right'},{x:53,y:67,a:'right'},{x:53,y:67,a:'right'},{x:52,y:68,a:'right'},{x:52,y:67,a:'right'},{x:51,y:67,a:'right'}]},
 {id:'platform',title:'Archipelago Platform',componentId:'archipelago-platform',tags:['Indonesia','Map','Diversity'],desc:'The archipelago platform transforms Indonesia’s geography into a learning surface linked to the national voice map and the 114-voice archive.',board:{x:33,y:63,a:'left'},pos:[{x:62,y:79,a:'right'},{x:61,y:79,a:'right'},{x:60,y:80,a:'right'},{x:51,y:81,a:'left'},{x:49,y:81,a:'left'},{x:49,y:81,a:'left'}]},
 {id:'qr-audio',title:'Interactive QR Audio Stations',componentId:'qr-station',tags:['QR','Audio','Archive'],desc:'The QR stations make the monument interactive. Visitors scan, listen, read transcripts, and enter the digital archive directly from the plaza.',board:{x:72,y:68,a:'alt'},pos:[{x:78,y:67,a:'right'},{x:78,y:69,a:'right'},{x:78,y:69,a:'right'},{x:80,y:68,a:'right'},{x:24,y:69,a:'left'},{x:23,y:69,a:'left'}]},
 {id:'paving',title:'Intelligibility Pattern Paving',componentId:'paving',tags:['Pronunciation','Intelligibility','ELF'],desc:'The paving engraves speech waves and phonetic motifs into public space. It communicates that pronunciation diversity is a field of meaning.',board:{x:43,y:82,a:'left'},pos:[{x:53,y:89,a:'right'},{x:51,y:90,a:'left'},{x:50,y:90,a:'left'},{x:50,y:90,a:'left'},{x:49,y:90,a:'left'},{x:49,y:90,a:'left'}]},
 {id:'night',title:'LED Night Illumination',componentId:'sound-spine',tags:['Lighting','Gallery','Public Space'],desc:'Night illumination makes the artwork visible after dark and symbolizes voices that continue to travel across time, space, and learning communities.',board:{x:90,y:83,a:'alt'},pos:[{x:52,y:79,a:'right'},{x:63,y:82,a:'right'},{x:65,y:82,a:'right'},{x:64,y:82,a:'right'},{x:61,y:82,a:'right'},{x:59,y:82,a:'right'}]}
];
let voices = [];
for (const p of PROVINCES){for (const s of SPEAKERS){voices.push({id:`${p.id}-${s.toLowerCase().replaceAll(' ','-')}`,provinceId:p.id,province:p.name,region:p.region,type:s,name:`${p.name} ${s}`,quote:`Representative ${s.toLowerCase()} from ${p.name} for Indonesian English intelligibility.`,transcript:`This ${s.toLowerCase()} from ${p.name} represents the Intelligibility Monument archive.`})}}
let angle=0, activeHotspot='wings', autoTimer=null, frameIndex=0, drag=null;
const $=id=>document.getElementById(id); const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const comp=id=>COMPONENTS.find(c=>c.id===id)||COMPONENTS[0]; const hot=id=>HOTSPOTS.find(h=>h.id===id)||HOTSPOTS[0];
function base(){return location.origin+location.pathname} function link(type,id){return `${base()}#${type}=${encodeURIComponent(id)}`} function qr(url){return `https://api.qrserver.com/v1/create-qr-code/?size=420x420&margin=12&data=${encodeURIComponent(url)}`}
function frameFor(a){return Math.floor((((a%360)+360)%360+30)/60)%FRAMES.length}
function renderViewer(){const f=FRAMES[frameIndex]; const img=$('viewerImg'); if(!img.src.endsWith(f.src)){img.classList.add('switching'); setTimeout(()=>{img.src=f.src; img.onload=()=>img.classList.remove('switching')},40)} $('viewLabel').textContent=`${f.label} · ${Math.round(angle)}°`; $('angleLabel').textContent=`${Math.round(angle)}°`; $('rotationSlider').value=Math.round(angle); renderHotspots();}
function setAngle(v){angle=((Number(v)||0)%360+360)%360; const next=frameFor(angle); if(next!==frameIndex) frameIndex=next; renderViewer();}
function step(delta){setAngle(angle+delta)}
function startAuto(){ if(autoTimer) clearInterval(autoTimer); autoTimer=setInterval(()=>step(2),110); $('autoRotate').textContent='Stop Rotation';}
function stopAuto(){ if(autoTimer) clearInterval(autoTimer); autoTimer=null; $('autoRotate').textContent='Auto Rotate';}
function toggleAuto(){autoTimer?stopAuto():startAuto()}
function renderHotspots(){const layer=$('hotspots'); layer.innerHTML=HOTSPOTS.map(h=>{const p=h.pos[frameIndex]||h.pos[0];return `<button class="spot ${p.a==='right'?'alt':''} ${h.id===activeHotspot?'active':''}" style="left:${p.x}%;top:${p.y}%" data-hot="${h.id}"><span class="dot">＋</span><span class="label">${esc(h.title)}</span></button>`}).join(''); layer.querySelectorAll('[data-hot]').forEach(b=>{b.addEventListener('pointerdown',e=>e.stopPropagation()); b.addEventListener('click',e=>{e.stopPropagation();selectHotspot(b.dataset.hot)})});}
function selectHotspot(id){activeHotspot=id; renderHotspots(); renderSidePanel(); renderDetailPanel(); toast(`Selected: ${hot(id).title}`)}
function renderSidePanel(){const h=hot(activeHotspot), c=comp(h.componentId), url=link('hotspot',h.id); $('sidePanel').innerHTML=`<p class="eyebrow">Selected Spot QR</p><h3>${esc(h.title)}</h3><img class="qr-side" src="${qr(url)}" alt="QR for ${esc(h.title)}"><p>${esc(h.desc)}</p><div class="tags">${h.tags.map(t=>`<span>${esc(t)}</span>`).join('')}</div><p><strong>Material</strong><br>${esc(c.material)}</p><p><strong>Meaning</strong><br>${esc(c.meaning)}</p><div class="actions"><button class="primary" onclick="openQr('${h.id}')">Open Large QR</button><button class="ghost" onclick="speakText('${esc(h.desc)}')">Listen</button></div>`}
function renderBoard(){const layer=$('boardHotspots'); layer.innerHTML=HOTSPOTS.map(h=>`<button class="spot ${h.board.a==='alt'?'alt':''}" style="left:${h.board.x}%;top:${h.board.y}%" data-board="${h.id}"><span class="dot">＋</span><span class="label">${esc(h.title)}</span></button>`).join(''); layer.querySelectorAll('[data-board]').forEach(b=>b.onclick=()=>selectHotspot(b.dataset.board));}
function renderDetailPanel(){const h=hot(activeHotspot), c=comp(h.componentId), url=link('hotspot',h.id); $('detailPanel').innerHTML=`<p class="eyebrow">Design-board selected spot</p><h3>${esc(h.title)}</h3><img class="qr-small" src="${qr(url)}"><p>${esc(h.desc)}</p><p><strong>Related material:</strong><br>${esc(c.name)} · ${esc(c.material)}</p>`}
function openQr(id=activeHotspot){const h=hot(id), url=link('hotspot',h.id); $('modalBody').innerHTML=`<p class="eyebrow">Large QR Access</p><h2>${esc(h.title)}</h2><div class="qr-card"><img src="${qr(url)}"><p>${esc(h.desc)}</p></div>`; $('modal').hidden=false}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),2500)}
function speakText(t){if(!('speechSynthesis'in window))return toast('Speech is not available.'); speechSynthesis.cancel(); const u=new SpeechSynthesisUtterance(t); u.lang='en-US'; speechSynthesis.speak(u)}
function renderVoices(){ $('voiceStats').innerHTML=`<div class="stat"><strong>${PROVINCES.length}</strong><span>Provinces</span></div><div class="stat"><strong>${voices.length}</strong><span>Voice records</span></div><div class="stat"><strong>${HOTSPOTS.length}</strong><span>QR spots</span></div><div class="stat"><strong>360°</strong><span>Auto rotation</span></div>`; $('provinceFilter').innerHTML='<option value="all">All provinces</option>'+PROVINCES.map(p=>`<option value="${p.id}">${p.name}</option>`).join(''); drawVoiceList();}
function drawVoiceList(){const q=($('voiceSearch')?.value||'').toLowerCase(), p=$('provinceFilter')?.value||'all', s=$('speakerFilter')?.value||'all'; const list=voices.filter(v=>(p==='all'||v.provinceId===p)&&(s==='all'||v.type===s)&&(`${v.name} ${v.quote}`.toLowerCase().includes(q))).slice(0,60); $('voiceList').innerHTML=list.map(v=>`<div class="voice-card"><h3>${esc(v.name)}</h3><p>${esc(v.quote)}</p><div class="tags"><span>${esc(v.province)}</span><span>${esc(v.type)}</span></div></div>`).join('')}
function renderMap(){const m=$('provinceMap'); m.innerHTML=PROVINCES.map(p=>`<button class="province-dot" style="left:${p.x}%;top:${p.y}%" title="${p.name}" onclick="filterProvince('${p.id}')"><span>${p.name}</span></button>`).join('')}
function filterProvince(id){$('provinceFilter').value=id; drawVoiceList(); location.hash='voices'}
function renderMaterials(){ $('materialsGrid').innerHTML=COMPONENTS.map(c=>`<div class="component-card"><h3>${esc(c.name)}</h3><p><strong>Material:</strong> ${esc(c.material)}</p><p>${esc(c.meaning)}</p></div>`).join('')}
function renderQR(){const targets=[{k:'platform',t:'Platform',u:base()},...HOTSPOTS.map(h=>({k:h.id,t:h.title,u:link('hotspot',h.id)}))]; $('qrSelect').innerHTML=targets.map(t=>`<option value="${t.k}">${esc(t.t)}</option>`).join(''); function update(){const t=targets.find(x=>x.k===$('qrSelect').value)||targets[0]; $('qrCard').innerHTML=`<h3>${esc(t.t)}</h3><img src="${qr(t.u)}"><p>${esc(t.u)}</p>`} $('qrSelect').onchange=update; update();}
function renderDossier(){ $('dossierContent').innerHTML=`<h3>The Intelligibility Monument</h3><p>A monumental public artwork celebrating Indonesian voices, intelligibility, and global academic communication through sculpture, sound, QR access, and interactive learning.</p><ul><li>38 provinces represented.</li><li>114 voice slots prepared.</li><li>7 hotspot QR points connected to the monument.</li></ul>`}
function setupAdmin(){ $('unlockAdmin').onclick=()=>{if($('pinInput').value===ADMIN_PIN){$('adminGate').hidden=true;$('adminPanel').hidden=false;toast('Admin unlocked.')}else toast('Incorrect PIN.')}; $('lockAdmin').onclick=()=>{$('adminGate').hidden=false;$('adminPanel').hidden=true}; $('exportData').onclick=()=>{const blob=new Blob([JSON.stringify({voices},null,2)],{type:'application/json'}); const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='intelligibility-monument-data.json';a.click()};}
function init(){renderViewer();renderSidePanel();renderBoard();renderDetailPanel();renderVoices();renderMap();renderMaterials();renderQR();renderDossier();setupAdmin();startAuto(); $('rotateLeft').onclick=()=>step(-60); $('rotateRight').onclick=()=>step(60); $('resetRotation').onclick=()=>setAngle(0); $('autoRotate').onclick=toggleAuto; $('selectedQrBtn').onclick=()=>openQr(activeHotspot); $('platformQrBtn').onclick=()=>{const url=base();$('modalBody').innerHTML=`<p class="eyebrow">Platform QR</p><h2>The Intelligibility Monument</h2><div class="qr-card"><img src="${qr(url)}"><p>${url}</p></div>`;$('modal').hidden=false}; $('rotationSlider').oninput=e=>setAngle(e.target.value); $('viewer').addEventListener('pointerdown',e=>{drag={x:e.clientX,a:angle};$('viewer').classList.add('dragging');$('viewer').setPointerCapture?.(e.pointerId);stopAuto()}); $('viewer').addEventListener('pointermove',e=>{if(drag)setAngle(drag.a+(e.clientX-drag.x)*.8)}); ['pointerup','pointercancel','pointerleave'].forEach(ev=>$('viewer').addEventListener(ev,()=>{drag=null;$('viewer').classList.remove('dragging')})); $('closeModal').onclick=()=>{$('modal').hidden=true}; document.querySelector('.modal-bg').onclick=()=>{$('modal').hidden=true}; $('voiceSearch').oninput=drawVoiceList; $('provinceFilter').onchange=drawVoiceList; $('speakerFilter').onchange=drawVoiceList; $('themeBtn').onclick=()=>document.body.classList.toggle('light')}
document.addEventListener('DOMContentLoaded',init);
